### PR TITLE
fix: `dwarf-4` compilation flag

### PR DESCRIPTION
**Pull request by Antonov548**

### CODE REVIEW

**Comment by Antonov548** [comment]
Checked in local Docker image. It works.

**Review by krlmlr — COMMENTED** [review]
Great! Do we need to add `-gdwarf4` to the other options too? Or is this specific to clang?

**Comment by Antonov548** [comment]
> Or is this specific to clang?

For me gcc didn't work at all. I can try one more time. But I saw some issues on github which was related to gcc. That it's not recommended to use for sanitizer.

**Comment by krlmlr** [comment]
It would be great to understand those issues, also in the igraph context. Thanks for digging into it!

**Pull request merged**
